// utils.js
export const cuisineDishList = [
  // Indian Cuisine
  "Litti Chokha(Bihar)",
  "Poha Jalebi(MP)",
  "Bikaneri Kachori(Rajasthan)",
  "Akki Roti(Karnataka)",
  "Paddu(TN)",
  "Ghugni Chaat(WB)",
  "Chole Bhaturey(Delhi)",
  "Tunde Kabab(Lucknow)",
  "Mirchi Bhaji(Hydrabad)",
  "Fuchka(WB)",
  "Kathi Rolls(WB)",
  "Pav Bhaji(Mumbai)",
  "Butter Chicken(Delhi)",
  "Vada Pav(Mumbai)",
  "Dal Makhani(Punjab)",
  "Momos(Sikkim)",
  "Aloo Gobhi(Punjab)",
  "Rogan Josh(Kashmir)",
  "Tandoori Chicken(Punjab)",
  // Chinese Cuisine
  "Kung Pulao Chicken",
  "Peking Roast Duck",
  "Tofu",
  "Chow Mein",
  "Cantonese Spring Roll",
  "DongPu Rou",
  "Chinese Hot and Sour Soup",
  "Sweet and Sour Pork",
  "Char Siu Pork",
  "Chicken Fried rice",
  // Italian Cuisine
  "Emilia-Romagna",
  "Risotto",
  "Carbonara Pasta",
  "Florentina Steak",
  "Gelato",
  "Tiramisu",
  "Bruschetta",
  "Gnocchi",
  "Pizza",
  "Arancini",
  "Ravioli",
  "Spaghetti alle Vongole",
  "Trofie al Pesto",
  "Lasagna",
  "Caprese Salad",
  // Mexican Cuisine
  "Taco",
  "Burritos",
  "Quesadillas",
  "Chilaquiles",
  "Pico De Gallo",
  "Guacamole",
  "Enchiladas",
  "Tostada",
  "Mole",
  "Salsa",
  "Churros",
  "Elote",
  "Fajitas",
  "Ceviche",
  "Tortillas",
  // Japanese Cuisine
  "Sushi",
  "Ramen",
  "Tempura",
  "Yakitori",
  "Sashimi",
  "Soba",
  "Udon",
  "Okonomiyaki",
  "Tonkatsu",
  "Unagi",
  "Onigiri",
  "Natto",
  "Tamago",
  "Yakizakana",
  "Korokke"
];
